# Generated by Django 4.0.3 on 2022-09-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_automobilevo_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
